### ISSUE TITLE
Migration issue with Django 2.1

### ISSUE THREAD

**Issue by akhilsp** [release-engineering/kobo#102]
Getting the following error when I do `python manage.py migrate`
```
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 82, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/db/migrations/loader.py", line 206, in build_graph
    self.load_disk()
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/django/db/migrations/loader.py", line 108, in load_disk
    migration_module = import_module(migration_path)
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/kobo/django/xmlrpc/migrations/0001_initial.py", line 8, in <module>
    class Migration(migrations.Migration):
  File "/home/akhilsp/.local/share/virtualenvs/Nitrate-9dTMyaLq/lib/python3.6/site-packages/kobo/django/xmlrpc/migrations/0001_initial.py", line 22, in Migration
    ('user', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

I was able to apply the migrations after editing  `/kobo/django/xmlrpc/migrations/0001_initial.py` by adding `on_delete=models.CASCADE` to line number 22.

Is there any work around without editing this?

**Comment by rohanpm** [comment]
Was released in kobo 0.9.0.
