### ISSUE TITLE
fix or deprecate kobo.django.StateEnumField

### ISSUE THREAD

**Issue by dmach** [release-engineering/kobo#2]
StateEnumField is broken:

```
ERROR: test_to_python (__main__.TestStateEnumField)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_types.py", line 206, in setUp
    self.field = StateEnumField(self.state_enum, default='NEW')
  File "/home/dmach/github/kobo-github/kobo/django/fields.py", line 48, in __init__
    super(StateEnumField, self).__init__(*args, **kwargs)
  File "/home/dmach/github/kobo-github/devel/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 162, in __init__
    self.choices = choices or []
TypeError: unbound method _set_choices() must be called with StateChoiceFormField instance as first argument (got StateEnumField instance instead)

```

**Comment by alexandrevicenzi** [comment]
I just want to add a note that `kobo.django.fields.StateEnumField` and `kobo.django.fields.JSONField` does not compile on versions >= Django 1.10 because it's base class `SubfieldBase` was removed.

JSONField could be replaced by `django.contrib.postgres.fields.JSONField` but only for PostgreSQL databases.
