### ISSUE TITLE
Python3 text encoding handled incorrectly for shortcuts.run

### ISSUE THREAD

**Issue by puiterwijk** [release-engineering/kobo#55]
This traceback was thrown when running pungi-4.1.21, which switched to python3:
````
Traceback (most recent call last):
  File "/usr/bin/pungi-koji", line 468, in <module>
    main()
  File "/usr/bin/pungi-koji", line 254, in main
    run_compose(compose, create_latest_link=create_latest_link, latest_link_status=latest_link_status)
  File "/usr/bin/pungi-koji", line 362, in run_compose
    init_phase.start()
  File "/usr/lib/python3.6/site-packages/pungi/phases/base.py", line 64, in start
    self.run()
  File "/usr/lib/python3.6/site-packages/pungi/phases/init.py", line 41, in run
    write_global_comps(self.compose)
  File "/usr/lib/python3.6/site-packages/pungi/phases/init.py", line 84, in write_global_comps
    get_file_from_scm(scm_dict, tmp_dir, logger=compose._logger)
  File "/usr/lib/python3.6/site-packages/pungi/wrappers/scm.py", line 249, in get_file_from_scm
    scm.export_file(scm_repo, i, scm_branch=scm_branch, target_dir=tmp_dir)
  File "/usr/lib/python3.6/site-packages/pungi/wrappers/scm.py", line 147, in export_file
    self.run_process_command(tmp_dir)
  File "/usr/lib/python3.6/site-packages/pungi/wrappers/scm.py", line 48, in run_process_command
    universal_newlines=True)
  File "h", line 326, in run
    lines = proc.stdout.read(buffer_size)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Frame decode in /usr/lib64/python3.6/encodings/ascii.py at line 26
<CODE>
````

**Comment by rohanpm** [comment]
I'm not sure this is a bug in kobo.shortcuts.run.  I see you pass universal_newlines=True.  It's mentioned in https://docs.python.org/3/library/subprocess.html#popen-objects that passing universal_newlines=True will cause Popen stdout to be treated as a text stream (i.e. it causes decoding to happen), rather than a byte stream.  I think that text stream would be using your default locale from the environment.

Is it possible that you're running a process which produces bytes not decodable according to your configured locale?  e.g. your locale uses ASCII and your command is producing UTF-8?  Can you share output of "locale" command where this is reproduced?

It seems that the correct ways to use kobo.shortcuts.run are:

- If you want text and you know the encoding used by the process you're running, then specify it in "encoding" argument.
- If you want text and you want to use the default encoding, you can omit "encoding" argument and provide universal_newlines=True.
- If you want bytes then provide neither argument.

In either of the text cases, if the process produces bytes which can't be decoded with the given encoding, then it'll crash, and I suspect that's what happened here.

**Comment by puiterwijk** [comment]
The issue we hit has been fixed on the Pungi side of things.
